name: Build and deploy Next.Js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: ${{ secrets.AZURE_APP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Enable Corepack + install deps
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install

      - name: Build and update deployment resources
        run: |
          pnpm turbo run build --filter=web
          mv ./apps/web/.next/static ./apps/web/.next/standalone/apps/web/.next/static
          mv ./apps/web/public ./apps/web/.next/standalone/apps/web/public

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./apps/web/.next/standalone
